preset: symfony

finder:
    exclude:
        - "spec"
    path:
        - "src"
        - "tests"

enabled:
    - long_array_syntax

disabled:
    - phpdoc_annotation_without_dot # This is still buggy: https://github.com/symfony/symfony/pull/19198
