language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

env:
    global:
        - TEST_COMMAND="composer test"

branches:
    except:
        - /^analysis-.*$/

matrix:
    allow_failures:
        - php: hhvm
    fast_finish: true
    include:
        - php: 7.0
          env: COVERAGE=true TEST_COMMAND="composer test-ci"

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi

install:
    - travis_retry composer update --prefer-dist --no-interaction

script:
    - $TEST_COMMAND

after_success:
    - if [[ $COVERAGE = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ $COVERAGE = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
